path_checkpoint: 'weights/'
filename_checkpoint: "bce_adam_2016_best_psnr.pth"

# Valid configuration
valid_data_path: "dataset/original/2016"
valid_gt_data_path: "dataset/ground_truth/2016"
valid_patch_size: 256
valid_batch_size: 1
valid_stride: 256
valid_kwargs:
  shuffle: False
  pin_memory: True
  batch_size: 1
  num_workers: 2