# Folder configuration
path_checkpoint: 'weights/'
filename_checkpoint: "bce_adam_2018_512_best_psnr.pth"
folder_destination: "bce_adam_2019"

# Dataset configuration
valid_data_path: "dataset/validation/2019/original"
valid_gt_data_path: "dataset/validation/2019/ground_truth"

# Valid configuration
valid_patch_size: 256
valid_batch_size: 1
valid_stride: 256
valid_kwargs:
  shuffle: False
  pin_memory: True
  batch_size: 1
  num_workers: 2