input_channels: 3
output_channels: 1

kind_loss: "custom_mse"
num_epochs: 150
path_checkpoint: 'weights/'
learning_rate: 1.5e-4

# Train configuration
train_data_path: "patches/train"
train_gt_data_path: "patches/train_gt"
train_split_size: 256
train_batch_size: 8
train_transform_variant: "adjust_sharpness"
train_kwargs:
  shuffle: True
  pin_memory: True
  batch_size: 8
  num_workers: 2

# Valid configuration
valid_data_path: "patches/valid"
valid_gt_data_path: "patches/valid_gt"
valid_split_size: 256
valid_batch_size: 1
valid_kwargs:
  shuffle: False
  pin_memory: True
  batch_size: 1
  num_workers: 2