input_channels: 3
output_channels: 1

kind_loss: "custom_mse"
kind_optimizer: "Adam"

num_epochs: 150
path_checkpoint: 'weights/'
learning_rate: 1.5e-4
seed: 110

optimizer:
  betas: [0.9, 0.95]
  eps: 1.0e-08
  weight_decay: 0.05
  amsgrad: False

# Train configuration
train_data_path: "patches/train"
train_gt_data_path: "patches/train_gt"
train_batch_size: 8
train_patch_size: 256
train_log_every: 100
train_transform_variant: "default"
train_max_value: 500
train_kwargs:
  shuffle: True
  pin_memory: True
  batch_size: 8
  num_workers: 2

# Valid configuration
valid_data_path: "patches/valid"
valid_gt_data_path: "patches/valid_gt"
valid_batch_size: 1
valid_patch_size: 256
valid_stride: 256
valid_kwargs:
  shuffle: False
  pin_memory: True
  batch_size: 1
  num_workers: 2