kind_loss: "binary_cross_entropy"
kind_optimizer: "Adam"
train_transform_variant: "default"

num_epochs: 150
path_checkpoint: 'weights/'
learning_rate: 1.5e-4
seed: 110
threshold: 0.5


# Train configuration
train_data_path: "patches/2009/train"
train_gt_data_path: "patches/2009/train_gt"
train_batch_size: 4
train_patch_size: 256
train_log_every: 100
train_max_value: 500
train_kwargs:
  shuffle: True
  pin_memory: True
  batch_size: 4
  num_workers: 2


# Valid configuration
valid_data_path: "dataset/original/2009"
valid_gt_data_path: "dataset/ground_truth/2009"
valid_batch_size: 1
valid_patch_size: 256
valid_stride: 256
valid_kwargs:
  shuffle: False
  pin_memory: True
  batch_size: 1
  num_workers: 2