paths:
  train: "dataset/original/"
  ground_truth: "dataset/ground_truth/"
  destination: "patches/"

validation_dataset: "2016"
testing_dataset: "2018"
patch_size: 384
patch_size_valid: 256
overlap_size: 192

